//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS {
    using System;
    using EMS;
    
    
    /// A rotating machine which may be used as a generator or motor.
    public class RotatingMachine : RegulatingCondEq {
        
        /// Nameplate apparent power rating for the unit.
        private System.Single? cim_ratedS;
        
        private const bool isRatedSMandatory = false;
        
        private const string _ratedSPrefix = "cim";
        
        public virtual float RatedS {
            get {
                return this.cim_ratedS.GetValueOrDefault();
            }
            set {
                this.cim_ratedS = value;
            }
        }
        
        public virtual bool RatedSHasValue {
            get {
                return this.cim_ratedS != null;
            }
        }
        
        public static bool IsRatedSMandatory {
            get {
                return isRatedSMandatory;
            }
        }
        
        public static string RatedSPrefix {
            get {
                return _ratedSPrefix;
            }
        }
    }
}
